version: '3'

services: 
  nginx: 
    depends_on:
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"

  frontend: 
 
    build: 
      dockerfile: Dockerfile
      context: ./frontend


  backend: 
  
    build: 
      dockerfile: Dockerfile
      context: ./backend
    restart: always
    ports: 
      - "3000:3000"
    # links: 
    #   - mongo

  # mongo:
  #   container_name: mongo
  #   build: mongo
  #   ports: 
  #     - "27017:27017"