
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      component: web
  template: 
    metadata: 
      labels: 
        component: web
    spec: 
      containers: 
        - name: frontend
          image: brandonjones085/frontend
          ports: 
            - containerPort: 4200



        
#192.168.99.100:31496
---
apiVersion: v1
kind: Service
metadata: 
  name: front
spec: 
  type: NodePort
  selector: 
    component: web
  ports: 
    - port: 80
      targetPort: 80

