
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      targets: nodes
      app: easy-notes-pod
  template: 
    metadata: 
      labels: 
        targets: nodes
        app: easy-notes-pod
    spec: 
      dnsPolicy: Default
      containers: 
        - name: server
          # env:
          #   - name: MONGO_URL
          #     value: mongodb+srv://brandon085:<password>@postdb.kn0jt.mongodb.net/<dbname>?retryWrites=true&w=majority
          image: brandonjones085/backend
          ports: 
            - containerPort: 3000
      


# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-load
# spec:
#   selector:
  
#     targets: nodes
#   ports:
#   - protocol: "TCP"
#     port: 3000
#     targetPort: 3000
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    targets: nodes
  name: easy-notes-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    targets: nodes
  type: ClusterIP